# Auth Endpoints

@host = http://127.0.0.1:5000
@baseUrl = {{host}}/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc1MTQ0NjExNywianRpIjoiNDAzYmM1MmMtYTgxMS00NDEzLWIwZTMtYTZhYzhiZDc5YTQ4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjMiLCJuYmYiOjE3NTE0NDYxMTcsImNzcmYiOiI3ZWU1OThlMy0xZGUxLTQ3ZjktYjA5OS1jNjA1NGUwZDY1MmIiLCJleHAiOjE3NTE0NDk3MTd9.SP7WXZtZQBhe6YmHyDsfE1WZOPKkSPrdU-Cwq3ewxMU


###

GET {{baseUrl}}/auth/users
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/auth/users/not-approved
Authorization: Bearer {{token}}

###

# Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "Chrizzl",
  "password": "sechallo",
  "vorname": "Christian",
  "nachname": "Zahn",
  "geburtsdatum": "2004-04-18",
  "rolle_id": 1,
  "email": "christian@localhost.de",
  "hausnummer": "17",
  "plz": "28816",
  "ort": "Stuhr",
  "strasse": "Ricarda-Huch-Str. ",
  "iban": "DE4309874087309401",
  "bic": "COBAHAETTETIHRGERNE",
  "angenommen": false
}

###

# Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "mathias4",
  "password": "sein_geburtstag",
  "vorname": "Mathias",
  "nachname": "Mitarbeiter",
  "geburtsdatum": "1998-05-14",
  "rolle_id": 3,
  "email": "mitarbeiterm@localhost.de",
  "hausnummer": "56",
  "plz": "28832",
  "ort": "Achim",
  "strasse": "Bremer Str.",
  "iban": "DE89370400440532013000",
  "bic": "COBADEFFXXX",
  "angenommen": true
}

###

PUT {{baseUrl}}/auth/users/7/approve
Authorization: Bearer {{token}}

###

# Login user
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "Admin",
  "password": "admin"
}

###

# Login user
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "mathias",
  "password": "sein_geburtstag"
}

###

# Get user profile (requires JWT token - replace YOUR_TOKEN_HERE with actual token)
GET {{baseUrl}}/auth/profile
Authorization: Bearer {{token}}

###

# Update user profile (requires JWT token)
PUT {{baseUrl}}/auth/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Vorname": "Maximilian",
  "Nachname": "Mustermann"
}

###

# Change password (requires JWT token)
PUT {{baseUrl}}/auth/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0OTA3MDQxNiwianRpIjoiMzg5OTY1MDctMTk4NS00OGIyLTgyMTktZjBkMTgyOTM2NTlmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NDkwNzA0MTYsImNzcmYiOiJjOTUzOTY0MC0wOWEzLTQ0YWUtYmFlNC02NzA4NmU0N2M0N2YiLCJleHAiOjE3NDkwNzQwMTZ9.BuMUFti6zva1xXvxa43h2H0OeXue3WudzeO_AUqM4AE

{
  "current_password": "password123",
  "new_password": "newpassword123"
}

###

# Refresh token (requires refresh token)
POST {{baseUrl}}/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0OTA3MDYzMCwianRpIjoiMDY4MzY4ZDktMDgwNy00YmVmLTkxYzMtZjA3ZmY5ODRkM2M0IiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiIxIiwibmJmIjoxNzQ5MDcwNjMwLCJjc3JmIjoiNDE1YTlkMWUtZmI5My00ODk2LTk0ZjgtZDUwYzVmYTgxNjgxIiwiZXhwIjoxNzUxNjYyNjMwfQ.TWuhnE4Jum4rdT0BLQevUundWnX9UxOJZ124oWcwGso

###

# Protected route example (requires JWT token)
GET {{baseUrl}}/auth/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0OTA3MDY0NCwianRpIjoiNTUwOTk1ZDEtZTE0Ni00OTQ1LWI3YzktOGViM2U4OGU2NGNjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NDkwNzA2NDQsImNzcmYiOiJlY2VlYzk4OC0yMGVhLTQ4YWItOGM2Mi1jNDdlY2MzYTcwOWEiLCJleHAiOjE3NDkwNzQyNDR9.pcTgL_FFZv9tM4ojg5bUGMm1ijC6l-eOGk37-SsUMCY
