# Fahrzeug Endpoints

@host = http://127.0.0.1:5000
@baseUrl = {{host}}/api


###

# GET all fahrzeugs
GET {{baseUrl}}/fahrzeug?detailed=true

###

# POST create new fahrzeug
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 1,
  "Kennzeichen": "HB-AX 123",
  "Reperaturzustand": "Gut",
  "Aktiv": true,
  "Reifen": "Winterreifen",
  "Kilometerstand": 50000,
  "LetzterService": "2024-01-15",
  "TuevDatum": "2025-12-31",
  "ErstzulassungsDatum": "2020-03-01"
}

###

# GET specific fahrzeug
GET {{baseUrl}}/fahrzeug/2

###

# PUT update fahrzeug
PUT {{baseUrl}}/fahrzeug/1
Content-Type: application/json

{
  "ModellID": 1,
  "Kennzeichen": "HB-AX 123",
  "Reperaturzustand": "Sehr gut",
  "Aktiv": true,
  "Reifen": "Sommerreifen",
  "Kilometerstand": 52000,
  "LetzterService": "2024-06-15",
  "TuevDatum": "2025-12-31",
  "ErstzulassungsDatum": "2020-03-01"
}

###

# DELETE fahrzeug
DELETE {{baseUrl}}/fahrzeug/1

### Add Multiple Example Vehicles ###

# POST create new fahrzeug 1
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 2,
  "Kennzeichen": "HB-CD 456",
  "Reperaturzustand": "Neuwertig",
  "Aktiv": true,
  "Reifen": "Sommerreifen",
  "Kilometerstand": 15000,
  "LetzterService": "2024-05-20",
  "TuevDatum": "2026-05-31",
  "ErstzulassungsDatum": "2022-05-15"
}

###

# POST create new fahrzeug 2
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 3,
  "Kennzeichen": "HB-EF 789",
  "Reperaturzustand": "Gebrauchsspuren",
  "Aktiv": true,
  "Reifen": "Allwetterreifen",
  "Kilometerstand": 75000,
  "LetzterService": "2023-11-10",
  "TuevDatum": "2025-11-30",
  "ErstzulassungsDatum": "2019-11-01"
}

###

# POST create new fahrzeug 3
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 4,
  "Kennzeichen": "HB-GH 101",
  "Reperaturzustand": "Gut",
  "Aktiv": false,
  "Reifen": "Winterreifen",
  "Kilometerstand": 120000,
  "LetzterService": "2024-02-01",
  "TuevDatum": "2025-02-28",
  "ErstzulassungsDatum": "2018-07-12"
}

###

# POST create new fahrzeug 4
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 5,
  "Kennzeichen": "HB-IJ 212",
  "Reperaturzustand": "Sehr gut",
  "Aktiv": true,
  "Reifen": "Sommerreifen",
  "Kilometerstand": 30000,
  "LetzterService": "2024-03-15",
  "TuevDatum": "2026-03-31",
  "ErstzulassungsDatum": "2021-03-10"
}

###

# POST create new fahrzeug 5
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 1, 
  "Kennzeichen": "HB-KL 323",
  "Reperaturzustand": "Akzeptabel",
  "Aktiv": true,
  "Reifen": "Winterreifen",
  "Kilometerstand": 95000,
  "LetzterService": "2023-09-01",
  "TuevDatum": "2025-09-30",
  "ErstzulassungsDatum": "2017-09-20"
}

###

# POST create new fahrzeug 6
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 6,
  "Kennzeichen": "HB-MN 434",
  "Reperaturzustand": "Gut",
  "Aktiv": true,
  "Reifen": "Allwetterreifen",
  "Kilometerstand": 60000,
  "LetzterService": "2024-01-10",
  "TuevDatum": "2026-01-31",
  "ErstzulassungsDatum": "2020-01-05"
}

###

# POST create new fahrzeug 7
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 7,
  "Kennzeichen": "HB-OP 545",
  "Reperaturzustand": "Neuwertig",
  "Aktiv": true,
  "Reifen": "Sommerreifen",
  "Kilometerstand": 5000,
  "LetzterService": "2024-06-01",
  "TuevDatum": "2026-06-30",
  "ErstzulassungsDatum": "2023-06-10"
}

###

# POST create new fahrzeug 8
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 8,
  "Kennzeichen": "HB-QR 656",
  "Reperaturzustand": "Gebrauchsspuren",
  "Aktiv": false,
  "Reifen": "Winterreifen",
  "Kilometerstand": 110000,
  "LetzterService": "2023-10-15",
  "TuevDatum": "2024-10-31",
  "ErstzulassungsDatum": "2016-10-01"
}

###

# POST create new fahrzeug 9
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 9,
  "Kennzeichen": "HB-ST 767",
  "Reperaturzustand": "Sehr gut",
  "Aktiv": true,
  "Reifen": "Sommerreifen",
  "Kilometerstand": 22000,
  "LetzterService": "2024-04-01",
  "TuevDatum": "2026-04-30",
  "ErstzulassungsDatum": "2022-04-15"
}

###

# POST create new fahrzeug 10
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 10,
  "Kennzeichen": "HB-UV 878",
  "Reperaturzustand": "Gut",
  "Aktiv": true,
  "Reifen": "Allwetterreifen",
  "Kilometerstand": 45000,
  "LetzterService": "2023-12-01",
  "TuevDatum": "2025-12-31",
  "ErstzulassungsDatum": "2021-12-10"
}

###

# POST create new fahrzeug 11
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 2, 
  "Kennzeichen": "HB-WX 989",
  "Reperaturzustand": "Akzeptabel",
  "Aktiv": true,
  "Reifen": "Winterreifen",
  "Kilometerstand": 88000,
  "LetzterService": "2024-01-20",
  "TuevDatum": "2025-01-31",
  "ErstzulassungsDatum": "2019-05-05"
}

###

# POST create new fahrzeug 12
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 3,
  "Kennzeichen": "HB-YZ 110",
  "Reperaturzustand": "Neuwertig",
  "Aktiv": false,
  "Reifen": "Sommerreifen",
  "Kilometerstand": 12000,
  "LetzterService": "2024-05-01",
  "TuevDatum": "2026-05-31",
  "ErstzulassungsDatum": "2023-04-20"
}

###

# POST create new fahrzeug 13
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 5,
  "Kennzeichen": "HB-AB 221",
  "Reperaturzustand": "Gut",
  "Aktiv": true,
  "Reifen": "Allwetterreifen",
  "Kilometerstand": 67000,
  "LetzterService": "2023-08-10",
  "TuevDatum": "2025-08-31",
  "ErstzulassungsDatum": "2020-08-01"
}

###

# POST create new fahrzeug 14
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 7,
  "Kennzeichen": "HB-BC 332",
  "Reperaturzustand": "Sehr gut",
  "Aktiv": true,
  "Reifen": "Winterreifen",
  "Kilometerstand": 33000,
  "LetzterService": "2024-02-15",
  "TuevDatum": "2026-02-28",
  "ErstzulassungsDatum": "2021-09-10"
}

###

# POST create new fahrzeug 15
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 1,
  "Kennzeichen": "HB-XY 999",
  "Reperaturzustand": "Gut",
  "Aktiv": true,
  "Reifen": "Sommerreifen",
  "Kilometerstand": 55000,
  "LetzterService": "2024-03-01",
  "TuevDatum": "2026-03-31",
  "ErstzulassungsDatum": "2021-03-15"
}

###

# POST create new fahrzeug 16
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 4,
  "Kennzeichen": "HB-ZZ 001",
  "Reperaturzustand": "Gebrauchsspuren",
  "Aktiv": true,
  "Reifen": "Allwetterreifen",
  "Kilometerstand": 92000,
  "LetzterService": "2023-10-01",
  "TuevDatum": "2025-10-31",
  "ErstzulassungsDatum": "2018-10-20"
}

###

# POST create new fahrzeug 17
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 6,
  "Kennzeichen": "HB-AA 112",
  "Reperaturzustand": "Neuwertig",
  "Aktiv": false,
  "Reifen": "Winterreifen",
  "Kilometerstand": 8000,
  "LetzterService": "2024-06-10",
  "TuevDatum": "2026-06-30",
  "ErstzulassungsDatum": "2023-06-01"
}

###

# POST create new fahrzeug 18
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 8,
  "Kennzeichen": "HB-BB 223",
  "Reperaturzustand": "Sehr gut",
  "Aktiv": true,
  "Reifen": "Sommerreifen",
  "Kilometerstand": 28000,
  "LetzterService": "2024-04-20",
  "TuevDatum": "2026-04-30",
  "ErstzulassungsDatum": "2022-04-01"
}

###

# POST create new fahrzeug 19
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 10,
  "Kennzeichen": "HB-CC 334",
  "Reperaturzustand": "Gut",
  "Aktiv": true,
  "Reifen": "Allwetterreifen",
  "Kilometerstand": 70000,
  "LetzterService": "2023-11-25",
  "TuevDatum": "2025-11-30",
  "ErstzulassungsDatum": "2019-11-15"
}

###

# POST create new fahrzeug 20
POST {{baseUrl}}/fahrzeug/
Content-Type: application/json

{
  "ModellID": 9,
  "Kennzeichen": "HB-DD 445",
  "Reperaturzustand": "Akzeptabel",
  "Aktiv": true,
  "Reifen": "Winterreifen",
  "Kilometerstand": 105000,
  "LetzterService": "2024-01-05",
  "TuevDatum": "2025-01-31",
  "ErstzulassungsDatum": "2017-05-10"
}

###
