# GeoDatum Endpoints

@host = http://127.0.0.1:5000
@baseUrl = {{host}}/api


###

# GET all geodatums
GET {{baseUrl}}/geodatum/

###

# POST create new geodatum
POST {{baseUrl}}/geodatum/
Content-Type: application/json

{
  "Longitude": 8.8017,
  "Latitude": 53.0793,
  "Zeit": "2024-06-04T10:30:00"
}

###

# GET specific geodatum
GET {{baseUrl}}/geodatum/1

###

# PUT update geodatum
PUT {{baseUrl}}/geodatum/1
Content-Type: application/json

{
  "Longitude": 8.8020,
  "Latitude": 53.0795,
  "Zeit": "2024-06-04T10:35:00"
}

###

# DELETE geodatum
DELETE {{baseUrl}}/geodatum/1
