# Reservierung Endpoints

@host = http://127.0.0.1:5000
@baseUrl = {{host}}/api


###

# Get all Reservierungen
GET {{baseUrl}}/reservierung/

###

# Create a new Reservierung
POST {{baseUrl}}/reservierung/
Content-Type: application/json

{
  "FahrzeugID": 1,
  "UserID": 1,
  "RechnungID": 1,
  "TarifID": 1,
  "StartDatum": "2024-12-10",
  "EndDatum": "2024-12-12",
  "Abholort": "Berlin",
  "AbholPlz": "10115",
  "Rueckgabeort": "Berlin",
  "RueckgabePlz": "10115"
}

###

# Create another Reservierung
POST {{baseUrl}}/reservierung/
Content-Type: application/json

{
  "FahrzeugID": 2,
  "UserID": 1,
  "RechnungID": 2,
  "TarifID": 1,
  "StartDatum": "2024-12-15",
  "EndDatum": "2024-12-17",
  "Abholort": "Berlin",
  "AbholPlz": "10115",
  "Rueckgabeort": "Hamburg",
  "RueckgabePlz": "20095"
}

###

# Get specific Reservierung by ID
GET {{baseUrl}}/reservierung/1

###

# Update specific Reservierung
PUT {{baseUrl}}/reservierung/1
Content-Type: application/json

{
  "FahrzeugID": 1,
  "UserID": 1,
  "RechnungID": 1,
  "TarifID": 2,
  "StartDatum": "2024-12-10",
  "EndDatum": "2024-12-13"
}

###

# Get all Reservierungen for a specific User
GET {{baseUrl}}/reservierung/6/rechnung

###

# Get all Reservierungen for a specific Fahrzeug
GET {{baseUrl}}/reservierung/fahrzeug/1

###

# Delete specific Reservierung
DELETE {{baseUrl}}/reservierung/5/rechnung
