# Rolle Endpoints

@host = http://127.0.0.1:5000
@baseUrl = {{host}}/api


###

# Get all Rollen
GET {{baseUrl}}/rolle/

###

# Create a new Rolle
POST {{baseUrl}}/rolle/
Content-Type: application/json

{
  "Bedeutung": "Customer Support"
}

###

# Get specific Rolle by ID
GET {{baseUrl}}/rolle/1

###

# Update specific Rolle
PUT {{baseUrl}}/rolle/1
Content-Type: application/json

{
  "Bedeutung": "Administrator"
}

###

# Delete specific Rolle
DELETE {{baseUrl}}/rolle/4
