# Schaden Endpoints

@host = http://127.0.0.1:5000
@baseUrl = {{host}}/api


###

# GET all schadens
GET {{baseUrl}}/schaden/

###

# POST create new schaden
POST {{baseUrl}}/schaden/
Content-Type: application/json

{
  "FahrzeugID": 1,
  "Beschreibung": "Kratzer am Kotflügel"
}

###

# GET specific schaden
GET {{baseUrl}}/schaden/1

###

# PUT update schaden
PUT {{baseUrl}}/schaden/1
Content-Type: application/json

{
  "FahrzeugID": 1,
  "Beschreibung": "Großer Kratzer am Kotflügel"
}

###

# DELETE schaden
DELETE {{baseUrl}}/schaden/1
